site: Andy Hazoume
url: #yoururl
title: Andy Hazoume
description: Data and Software Engineer
author:
  name: Andy Hazoume
  avatar: https://www.gravatar.com/avatar/4296aafe308c5efe0bf3c04de129fbd4.jpg
  email: andy.hazoume@gmail.com
  url: andyhazou.me
permalink: pretty

baseurl: ""

# highlighter: none
highlighter: rouge

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"